# Generated and used by Cassie::Configuration.
#
# Per-enviornment options are passed to `cassandra-driver` during
# cluster creation and used to determine default keyspace for session creation.
# See valid options and values for cluster configuration at:
# http://datastax.github.io/ruby-driver/api/#cluster-class_method

development:
  hosts:
    - 127.0.0.1
  port: 9042
  keyspace: timebomb_api_development

test:
  hosts:
    - 127.0.0.1
  port: 9042
  idle_timeout: null
  keyspace: cassie_test
